language: objective-c
osx_image: xcode9.2

env:
  global:
  - MODULE_NAME=ti.optimizationpreferences

cache:
  directories:
  - node_modules
  - $HOME/android-sdk
  - $HOME/Library/Caches/Homebrew
  - $HOME/Library/Application\ Support/Titanium
  timeout: 600

before_install:
- MODULE_ROOT=$PWD
- brew update > /dev/null
- brew install nvm
- nvm install v6.12.3
- npm config delete prefix
- nvm use v6.12.3
- brew cask uninstall oclint
- brew tap oclint/formulae
- brew install oclint
- oclint -version

install:
- cd $MODULE_ROOT
- curl -o install.sh https://raw.githubusercontent.com/jvandijk/ci/master/travis/install.sh
- source install.sh -s "--branch 7_0_X" -a 25

before_script:
- curl -o script.sh https://raw.githubusercontent.com/hansemannn/ci/master/travis/script.sh
- chmod +x script.sh

script:
- MODULE_ROOT=$MODULE_ROOT bash script.sh

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: lC/GVUGk3u7Vrw8wHVQ6tEPUFlMXJNdTO78N+K9CgiRR4e/ZSY04foFcdFOm4De6QK6PNULqaUaAzDQIfpA7YM+sSx5OSZJeub5qw7WnSL0UKHmImc80vOM5HR7LFgyvUKTjGlCxM0IkXF+1oo8l/9tou4K5RAKvb4JUvjBWRkGqQAWHheCp7lUVJyUMQ60v+1PlzTz3AuvKFbrFcpA/E8/D+YayzwmNZcxfQsscEDHeCkNyTwqBv4+bexmcvYiIc7fI/6XOTyqXUAEVd+jrrzW8VLTcB5D9E19NOdAu8296VXizOXiJtKFSz9NW8XPMLcaPwKv2r4ooq+tAjlqgTsGQv4NwQcImSUow/EnN5ZUdN70wXhEls1+iTqBKPsYNmnD9oazPvoL0sLYsKqehkT5OtfTRcSvnXzl0st+XaMRRz10t0yoYZ6oDr9CLuN1F18t1yLX8TlZSu1915wzoxQN1zr678Bx6uUgqfPw+fYkh0rzCnCtDcL5qI7DHP5CUszf4nzPPJIB5zzyHOgjj8VjQVnqx+gxzCfxZ8+tCTczXWvCmALqtgzsoueAwh34qC3Q9bEj6CDe0FiTxrH4YERyImxytbazvXDZO/F21jucLh9Oyj5dN5nefedgDPUBpuHiavHjJPRB75JumGAAHWWrlU8dhul8bpv1JBqvBCnM=
  file:
    - $MODULE_ROOT/android/dist/ti.optimizationpreferences-android-${TRAVIS_TAG}.zip
  on:
    repo: williamrijksen/ti.optimizationpreferences
    tags: true